/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f36da557-d054-4264-bd9e-a2f22a7191e6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WFPDVAkVy",
    "aws_user_pools_web_client_id": "7doi3lqt5ompea1t4ad9dna1at",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://r2ounxknr5bmzcyrv25ylnbjby.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
